apiVersion: batch/v1
kind: CronJob
metadata:
  name: vayutwin-pipeline
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: data-ingestion
            image: vayutwin-backend:latest
            imagePullPolicy: Never
            volumeMounts:
            - name: shared-data
              mountPath: /shared
          restartPolicy: OnFailure
          volumes:
          - name: shared-data
            persistentVolumeClaim:
              claimName: shared-data-pvc